---
title: "RCTD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

rmarkdown::render(input = paste0("./Seurat_human_LN.Rmd"), 
                  output_format = "html_document", 
                  output_file=paste0("./Seurat_human_LN.html"))

## Seurat V3

```{r }
library(Matrix)
library(data.table)
library(Seurat)
library(SeuratDisk)
```

```{r}
# read cell2location model results
results_folder = '/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/lymph_nodes_analysis/'

reg_mod_name = 'RegressionNBV4Torch_57covariates_73260cells_10237genes'
reg_path = paste0(results_folder, 'regression_model/', reg_mod_name, '/')
Convert(paste0(reg_path,'sc.h5ad'), dest = "h5seurat", overwrite = TRUE)

sc_seu = LoadH5Seurat(paste0(reg_path,'sc.h5seurat'))
Idents(sc_seu) = sc_seu$Subset
```

```{r}
run_name = 'CoLocationModelNB4V2_34clusters_4039locations_10241genes_input_inferred_V4_batch1024_l2_0001_n_comb50_5_cps5_fpc3_alpha001'
sp_data_path = paste0(results_folder, run_name, '/')

Convert(paste0(sp_data_path, 'sp_with_clusters_for_seurat.h5ad'), dest = "h5seurat", overwrite = TRUE)
sp_seu = LoadH5Seurat(paste0(sp_data_path, 'sp_with_clusters_for_seurat.h5seurat'))

sp_seu = sp_seu[!duplicated(sp_seu@assays$RNA@meta.features$SYMBOL),]
rownames(sp_seu@assays$RNA@meta.features) = sp_seu@assays$RNA@meta.features$SYMBOL
rownames(sp_seu@assays$RNA@counts) = sp_seu@assays$RNA@meta.features$SYMBOL
rownames(sp_seu@assays$RNA@data) = sp_seu@assays$RNA@meta.features$SYMBOL
```

```{r}
# the column for annotations
sc_seu@meta.data$Subset = factor(as.character(sc_seu@meta.data$Subset))
```

## running Seurat PCA

```{r seurat}
library(dplyr)

sc_seu <- SCTransform(sc_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)
sp_seu <- SCTransform(sp_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)

start_time <- Sys.time()

anchors <- FindTransferAnchors(reference = sc_seu, query = sp_seu, normalization.method = "SCT")

predictions.assay <- TransferData(anchorset = anchors, refdata = sc_seu$Subset,
                                  weight.reduction = 'pcaproject')

end_time <- Sys.time()
end_time - start_time
```

```{r}
saveRDS(object = predictions.assay,
        file = "/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/lymph_nodes_analysis/seurat_new/results_pca.RDS")

predictions.assay$spot = rownames(predictions.assay)
write.csv(predictions.assay, '/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/lymph_nodes_analysis/seurat_new/results_pca.csv')
predictions.assay[1:5, 1:5]
```

## running Seurat CCA

```{r seurat_cca}
library(dplyr)

sc_seu <- SCTransform(sc_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)
sp_seu <- SCTransform(sp_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)

start_time <- Sys.time()

anchors <- FindTransferAnchors(reference = sc_seu, query = sp_seu, normalization.method = "SCT", reduction='cca')

predictions.assay <- TransferData(anchorset = anchors, refdata = sc_seu$Subset,
                                  weight.reduction = 'cca')

end_time <- Sys.time()
end_time - start_time
```

```{r}
saveRDS(object = predictions.assay,
        file = "/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/lymph_nodes_analysis/seurat_new/results_cca.RDS")

predictions.assay$spot = rownames(predictions.assay)
write.csv(predictions.assay, '/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/lymph_nodes_analysis/seurat_new/results_cca.csv')
predictions.assay[1:5, 1:5]
```
