---
title: "SPOTlight"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

rmarkdown::render(input = paste0("./SPOTlight_mouse_brain.Rmd"), 
                  output_format = "html_document", 
                  output_file=paste0("./SPOTlight_mouse_brain.html"))

## SPOTlight

```{r }
library(Matrix)
library(data.table)
library(Seurat)
library(SeuratDisk)
library(dplyr)
library(SPOTlight)
library(Seurat)
```

```{r}
sp_data_folder = '/nfs/team205/vk7/sanger_projects/cell2location_proj/notebooks/data/visium_cortex_trial/'
sc_data_folder = '/nfs/team205/vk7/sanger_projects/cell2location_proj/notebooks/data/mouse_visium_snrna/'
results_folder = '/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/mouse_visium_snrna/'

reg_mod_name = 'RegressionNBV2Torch_65covariates_40532cells_12819genes'
reg_path = paste0(results_folder, 'regression_model/', reg_mod_name, '/')
Convert(paste0(reg_path,'sc.h5ad'), dest = "h5seurat", overwrite = TRUE)

sc_seu = LoadH5Seurat(paste0(reg_path,'sc.h5seurat'))
Idents(sc_seu) = sc_seu$annotation_1
```
```{r}
run_name = 'LocationModelLinearDependentWMultiExperiment_59clusters_14968locations_12809genes_n_comb50_mean_var5_inferred_30k'
sp_data_path = paste0(results_folder, run_name, '/')

Convert(paste0(sp_data_path, 'sp_with_clusters.h5ad'), dest = "h5seurat", overwrite = TRUE)
sp_seu = LoadH5Seurat(paste0(sp_data_path, 'sp_with_clusters.h5seurat'))
```

```{r}
# the column for annotations is hard-coded
sc_seu@meta.data$annotation_1 = factor(sc_seu@meta.data$annotation_1)
```

## running SPOTlight

```{r seurat}

sc_seu <- SCTransform(sc_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)
sp_seu <- SCTransform(sp_seu, verbose = FALSE) %>% RunPCA(verbose = FALSE)

start_time <- Sys.time()

#### Extract the top marker genes from each cluster ####
Seurat::Idents(object = sc_seu) <- sc_seu@meta.data$annotation_1
cluster_markers_all <- Seurat::FindAllMarkers(object = sc_seu, 
                                              assay = "RNA",
                                              slot = "data",
                                              verbose = TRUE, 
                                              only.pos = TRUE, 
                                              logfc.threshold = 1,
                                              min.pct = 0.9)


set.seed(123)
spotlight_ls <- spotlight_deconvolution(se_sc = sc_seu,
                                      counts_spatial = sp_seu@assays$RNA@counts,
                                      clust_vr = "annotation_1",
                                      cluster_markers = cluster_markers_all,
                                      cl_n = 100, # 100 by default
                                      hvg = 5000,
                                      ntop = NULL,
                                      transf = "uv",
                                      method = "nsNMF",
                                      min_cont = 0.09)

end_time <- Sys.time()
end_time - start_time
```

```{r}
saveRDS(object = spotlight_ls,
        file = "/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/mouse_visium_snrna/SPOTlight/results_hvg5k.RDS")

decon_mtrx <- spotlight_ls[[2]]
rownames(decon_mtrx) = colnames(sp_seu)

library(data.table)
decon_df = as.data.table(decon_mtrx, keep.rownames=TRUE)
fwrite(decon_df, "/nfs/team205/vk7/sanger_projects/cell2location_paper/notebooks/selected_results/benchmarking/mouse_visium_snrna/SPOTlight/results_hvg5k.csv")
```

